default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3
  # database: postgres
  # username: postgres
  # password: H76baaag.

test:
  <<: *default
  database: db/test.sqlite3
  # database: glenn

production:
  <<: *default
  database: db/production.sqlite3
  # database: glenn_production

# production:
# adapter: postgresql
# encoding: unicode
#   database: production
#   host: <%= ENV['DATABASE_HOST'] %>
#   pool: 5